platform :osx, '10.11'
source 'https://github.com/CocoaPods/Specs.git'
xcodeproj 'manager/manager.xcodeproj'

pod 'Sparkle'
# pod 'ReactiveCocoa'
# pod 'ReactiveViewModel'
pod 'AFNetworking'
# pod 'STPrivilegedTask'
# pod 'ReactiveCocoaIO'
# pod 'ReactiveCocoaLayout'
# pod 'CocoaAsyncSocket'
# pod 'PocketSocket'
# pod 'SocketRocket'
# pod 'SBJson4', '~> 4.0.1'
pod 'NMSSH'