/* Generated by CMake build scripts, manual changes will be lost */

#define HAVE_ZLIB
#define HAVE_LIBBZ2
#define HAVE_LZMA
#define HAVE_MEMORY_SPTR
/* #undef HAVE_TR1_MEMORY */
/* #undef HAVE_BOOST_SMARTPTR */
#define SIZEOF_LONG 
#define SIZEOF_INT 
#define HAVE_WORDEXP
#define HAVE_GLOB
/* #undef HAVE_FADVISE */
#define HAVE_MADVISE
/* #undef HAVE_LINUX_FALLOCATE */
/* #undef HAVE_LINUX_SENDFILE */
/* #undef WORDS_BIGENDIAN */
#define HAVE_DLOPEN
#define HAVE_PREAD
/* #undef HAVE_LINUX_SPLICE */
/* #undef HAVE_DAEMON */
/* #undef HAVE_LIBWRAP */
#define HAVE_SYS_MOUNT_H
/* #undef HAVE_SYS_VFS_H */
#define PTHREAD_COND_TIMEDWAIT_TIME_RANGE_OK
/* #undef HAVE_SSL */
