Vagrant.require_version ">= 1.4.3"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	# Define base image
    config.vm.box = "ubuntu/trusty64"

	# node for sharing bigdata packages between master and slaves
	config.vm.synced_folder "/bigpkg", "/bigpkg"

	numNodes = 3
	r = numNodes..1
	(r.first).downto(r.last).each do |i|
		config.vm.define "pc-node#{i}" do |node|
			node.vm.box = "precise64"
			node.vm.provider "virtualbox" do |v|
			  v.name = "pc-node#{i}"
			  v.customize ["modifyvm", :id, "--memory", "1024"]
			  v.customize ["modifyvm", :id, "--cpus", "1"]
			  v.customize ["modifyvm", :id, "--chipset", "ich9"]
			end

			node.vm.network :private_network, ip: "10.211.55.2%02d" % i
			node.vm.hostname = "pc-node#{i}"

			# path to save
            node.vm.synced_folder "/pocket/nodes/pc-node#{i}", "/pocket", id: "vagrant-root",
                owner: "pocket",
                group: "pocket",
                mount_options: ["dmode=755,fmode=644"]

			node.vm.provision "shell", path: "scripts/setup-nodes.sh"
			node.vm.provision "shell" do |s|
				s.path = "scripts/setup-nodes.sh"
				s.args = "-t #{numNodes}"
			end

			node.vm.provision "shell", path: "scripts/setup-basic-packages.sh"
			node.vm.provision "shell", path: "scripts/increase_swap.sh", args: "2048"

		end
	end
end
